spring:
  config:
    activate:
      on-profile: cli-demo

safeair:
  cli:
    suppress-telemetry-output: ${SAFEAIR_CLI_SUPPRESS_TELEMETRY_OUTPUT:true}
  profile1:
    emulators:
      - emulatorId: CLI-EMU-ALPHA
        updateIntervalSec: 1
        roomSquareMeters: 28
        windowCount: 1
        sensorTypes: [1, 2, 3, 4]
        deviceTypes: [1, 2, 3]

      - emulatorId: CLI-EMU-BRAVO
        updateIntervalSec: 2
        roomSquareMeters: 45
        windowCount: 3
        sensorTypes: [2, 4]
        deviceTypes: [1, 3]

      - emulatorId: CLI-EMU-CHARLIE
        updateIntervalSec: 3
        roomSquareMeters: 62
        windowCount: 0
        sensorTypes: [1, 3, 4]
        deviceTypes: [2, 3]

      - emulatorId: CLI-EMU-DELTA
        updateIntervalSec: 1
        roomSquareMeters: 80
        windowCount: 4
        sensorTypes: [1, 2]
        deviceTypes: [1, 1, 2, 3]
